[project]
authors = ["Simon Golbert <simongolbert@proton.me>"]
channels = ["conda-forge"]
description = "Boolean backpropagation research"
name = "bbp-research"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[system-requirements]
cuda = "12.2"

[tasks]
bench = "pytest -m benchmark --benchmark-sort=name --benchmark-columns=mean"
lint = "pylint setup.py src/bitwise2 tests/test_bitwise2"
test = "pytest -m 'not benchmark'"

[tasks.build-ext]
env = { TORCH_CUDA_ARCH_LIST = "7.0;8.0;8.6;8.9" }
cmd = """
    python setup.py build && \
    stubgen --include-docstrings -o build/lib.linux-x86_64-cpython-312 \
        -m bitwise2_ext_cpu \
        -m bitwise2_ext_cuda
"""

[dependencies]
ipykernel = ">=6.29.5,<7"
libgfortran5 = ">=14.2.0,<15"
matplotlib = ">=3.10.1,<4"
mypy = ">=1.16.0,<2"
numpy = ">=2.2.3,<3"
pylint = ">=3.3.7,<4"
pytest = ">=8.3.4,<9"
pytorch = ">=2.5.1,<3"
ninja = ">=1.12.1,<2"
setuptools = ">=75.8.2,<76"
pytest-benchmark = ">=5.1.0,<6"

[target.osx-arm64.dependencies]
cxx-compiler = "*"

[target.linux-64.dependencies]
cuda-nvcc = "12.2.*"
gxx_linux-64 = "12.*"
pytorch-gpu = ">=2.5.1,<3"
