[project]
authors = ["Simon Golbert <simongolbert@proton.me>"]
channels = ["conda-forge"]
description = "My research work"
name = "bbp-research"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[system-requirements]
cuda = "12.0"

[tasks]

[dependencies]
ipykernel = ">=6.29.5,<7"
libgfortran5 = ">=14.2.0,<15"
matplotlib = ">=3.10.1,<4"
numpy = ">=2.2.3,<3"
pylint = ">=3.3.7,<4"
pytest = ">=8.3.4,<9"
pytorch = ">=2.5.1,<3"
