[project]
authors = ["Simon Golbert <simongolbert@proton.me>"]
channels = ["conda-forge"]
description = "My research work"
name = "research"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
pytorch = ">=2.5.1,<3"
ipykernel = ">=6.29.5,<7"
pytest = ">=8.3.4,<9"
matplotlib = ">=3.10.1,<4"
numpy = ">=2.2.3,<3"
pylint = ">=3.3.7,<4"
libgfortran5 = ">=14.2.0,<15"
