[project]
authors = ["Simon Golbert <simongolbert@proton.me>"]
channels = ["conda-forge"]
description = "Boolean backpropagation research"
name = "bbp-research"
platforms = ["linux-64", "osx-arm64"]
version = "0.1.0"

[system-requirements]
cuda = "12.2"

[tasks]
lint = "pylint setup.py src/bitwise2 tests/test_bitwise2"
test = "pytest"

[tasks.build-ext]
cmd = "python setup.py build"
env = { TORCH_CUDA_ARCH_LIST = "7.0;8.0;8.6;8.9" }

[dependencies]
ipykernel = ">=6.29.5,<7"
libgfortran5 = ">=14.2.0,<15"
matplotlib = ">=3.10.1,<4"
numpy = ">=2.2.3,<3"
pylint = ">=3.3.7,<4"
pytest = ">=8.3.4,<9"
pytorch = ">=2.5.1,<3"
ninja = ">=1.12.1,<2"
setuptools = ">=75.8.2,<76"

[target.osx-arm64.dependencies]
cxx-compiler = "*"

[target.linux-64.dependencies]
cuda-nvcc = "12.2.*"
gxx_linux-64 = "12.*"
pytorch-gpu = ">=2.5.1,<3"
